function [ X , T ] = get_properties_files(  )

root = fullfile(fileparts(fileparts(mfilename('fullpath'))),'data');

X={ fullfile(root,'210W_pm.properties'),...
    fullfile(root,'210W_pm_alinea_noqo.properties'),...
    fullfile(root,'210W_pm_alinea_qo.properties'),...
    fullfile(root,'210W_pm_adjoint_noqo.properties'),...
    fullfile(root,'210W_pm_adjoint_qo.properties')};


T={ 'no control',...
    'alinea no queue override',...
    'alinea with queue override',...
    'adjoint no queue override',...
    'adjoint with queue override'};