clear
close all

% 1. crop in space and time
reduce_freeway_scenario( ...
    'C:\Users\gomes\code\L0\L0-mpc-demo\data\210W_pm.xml' , ...
    'C:\Users\gomes\code\L0\L0-mpc-demo\data\210W_pm_cropped.xml', ...
    142,145,181,15,21);

% 2. remove source links
remove_sources( ...
    'C:\Users\gomes\code\L0\L0-mpc-demo\data\210W_pm_cropped.xml' , ...
    'C:\Users\gomes\code\L0\L0-mpc-demo\data\210W_pm_cropped_L0.xml' );

% 3. generate alinea scenarios
add_alinea( ...
    'C:\Users\gomes\code\L0\L0-mpc-demo\data\210W_pm_cropped_L0.xml' , ...
    'C:\Users\gomes\code\L0\L0-mpc-demo\data\210W_pm_alinea_qo.xml' , ...
    30 , ...
    false , ...
    50.0 * 1609.344 / 3600.0 , ...
    'up' );

add_alinea( ...
    'C:\Users\gomes\code\L0\L0-mpc-demo\data\210W_pm_cropped_L0.xml' , ...
    'C:\Users\gomes\code\L0\L0-mpc-demo\data\210W_pm_alinea_noqo.xml' , ...
    inf , ...
    false , ...
    50.0 * 1609.344 / 3600.0 , ...
    'up' );

% 4. generate adjoint scenarios
add_adjoint( ...
    'C:\Users\gomes\code\L0\L0-mpc-demo\data\210W_pm_cropped_L0.xml' , ...
    'C:\Users\gomes\code\L0\L0-mpc-demo\data\210W_pm_adjoint_qo.xml' , ...
    30 , ...
    false );

add_adjoint( ...
    'C:\Users\gomes\code\L0\L0-mpc-demo\data\210W_pm_cropped_L0.xml' , ...
    'C:\Users\gomes\code\L0\L0-mpc-demo\data\210W_pm_adjoint_noqo.xml' , ...
    inf , ...
    false );
